version: "3.9"
services:
    backend:
        image: demo
        container_name: demo
        build:
            context: ./demo
        ports:
            - "9000:80"
    frontend:
        image: demo-ui
        container_name: demo-ui
        build:
            context: ./my-demo-ui
        ports:
            - "4200:80"
        depends_on:
            - backend    